#!/usr/bin/env sh

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config border_width 1
bspc config window_gap 0

bspc config normal_border_color "#181a23"
bspc config active_border_color "#181a23"
bspc config focused_border_color "#bd93f9"
bspc config presel_feedback_color "#bd93f9"

# Extra padding for polybar
bspc config top_padding 0
bspc config bottom_padding 0

bspc config -m primary top_padding 0

if [ $DUALMONITOR == "yes" ]; then
  bspc config -m primary bottom_padding 50
  bspc config -m 'primary#next' top_padding 0
  bspc config -m 'primary#next' bottom_padding 50
else
  bspc config -m primary bottom_padding 42
fi
