## reference
## https://github.com/nix-community/home-manager/blob/master/modules/programs/wezterm.nix

{ options, config, lib, pkgs, ... }:

with lib;
with lib.my;
let cfg = config.modules.desktop.term.wezterm;
    tomlFormat = pkgs.formats.toml {};
    configDir = config.dotfiles.configDir;

in {
  options.modules.desktop.term.wezterm = {
    enable = mkBoolOpt false;

    extraConfig = mkOption {
      type = types.lines;
      default = ''
        return {}
      '';
      example = literalExpression ''
        -- Your lua code / config here
        local mylib = require 'mylib';
        return {
          usemylib = mylib.do_fun();
          font = wezterm.font("JetBrains Mono"),
          font_size = 28.0,
          color_scheme = "Tomorrow Night",
          hide_tab_bar_if_only_one_tab = true,
          #default_prog = { "zsh", "--login", "-c", "tmux attach -t dev || tmux new -s dev" },
          default_prog = { "fish", "--login", "-c", "tmux attach -t dev || tmux new -s dev" },
          keys = {
            {key="n", mods="SHIFT|CTRL", action="ToggleFullScreen"},
          }
        }
      '';
      description = ''
        Extra configuration written to
        <filename>$XDG_CONFIG_HOME/wezterm/wezterm.lua</filename>. See
        <link xlink:href="https://wezfurlong.org/wezterm/config/files.html"/>
        how to configure.
      '';
    };

    colorSchemes = mkOption {
      type = types.attrsOf (tomlFormat.type);
      default = { };
      example = literalExpression ''
        myCoolTheme = {
          ansi = [
            "#222222" "#D14949" "#48874F" "#AFA75A"
            "#599797" "#8F6089" "#5C9FA8" "#8C8C8C"
          ];
          brights = [
            "#444444" "#FF6D6D" "#89FF95" "#FFF484"
            "#97DDFF" "#FDAAF2" "#85F5DA" "#E9E9E9"
          ];
          background = "#1B1B1B";
          cursor_bg = "#BEAF8A";
          cursor_border = "#BEAF8A";
          cursor_fg = "#1B1B1B";
          foreground = "#BEAF8A";
          selection_bg = "#444444";
          selection_fg = "#E9E9E9";
        };
      '';
      description = ''
        Attribute set of additional color schemes to be written to
        <filename>$XDG_CONFIG_HOME/wezterm/colors</filename>, where each key is
        taken as the name of the corresponding color scheme. See
        <link xlink:href="https://wezfurlong.org/wezterm/config/appearance.html#defining-a-color-scheme-in-a-separate-file"/>
        for more details of the TOML color scheme format.
      '';
    };
  };


  config = mkIf cfg.enable {
    user.packages = with pkgs; [
      wezterm
      #(makeDesktopItem {
      #  name = "wezterm";
      #  desktopName = "Wez Terminal";
      #  genericName = "Wez terminal";
      #  icon = "utilities-terminal";
      #  exec = "${xst}/bin/wezterm";
      #  categories = [ "Development" "System" "Utility" ];
      #})
    ];

    ## home.configFile = {
    ##   "wezterm/wezterm.lua".text = ''
    ##     -- Generated by Home Manager.
    ##     -- See https://wezfurlong.org/wezterm/
    ##     -- Add config folder to watchlist for config reloads.
    ##     local wezterm = require 'wezterm';
    ##     wezterm.add_to_config_reload_watch_list(wezterm.config_dir)
    ##     ${cfg.extraConfig}
    ##   '';
    ## } // mapAttrs' (name: value:
    ##   nameValuePair "wezterm/colors/${name}.toml" {
    ##     source = tomlFormat.generate "${name}.toml" { colors = value; };
    ##   }) cfg.colorSchemes;

    home.configFile = {
      "wezterm" = { source = "${configDir}/wezterm"; recursive = true; };
    };

  };
}
