#!/usr/bin/env sh

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config normal_border_color "#0d0f11"
bspc config active_border_color "#16181a"
bspc config focused_border_color "#5c5e5e"
bspc config presel_feedback_color "#bd93f9" # TODO

bspc config border_width 1
bspc config window_gap -1

bspc config top_padding 1
bspc config bottom_padding 1
bspc config left_padding 1
bspc config right_padding 1
#bspc config -m "$MONITOR" top_padding 31

# Extra padding for polybar
#bspc config top_padding 0
#bspc config bottom_padding 0
#bspc config -m primary top_padding 0

#if [ $DUALMONITOR == "yes" ]; then
#    bspc config -m primary bottom_padding 50
#    bspc config -m 'primary#next' top_padding 0
#    bspc config -m 'primary#next' bottom_padding 50
#else
#    bspc config -m primary bottom_padding 50
#fi

if [ $DUALMONITOR == "yes" ]; then
    bspc config -m primary top_padding 50
    bspc config -m 'primary#next' top_padding 50
else
    bspc config -m primary top_padding 50
fi
