# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "vmw_pvscsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "cifs" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  services.xserver.videoDrivers = [ "vmware" ];
  virtualisation.vmware.guest.enable = true;
  services.logrotate.checkConfig = false;

  #time.hardwareClockInLocalTime = true;
  #networking.timeServers = options.networking.timeServers.default;
  #services.ntp.enable = true;

  #fileSystems."/" =
  #  { device = "/dev/disk/by-uuid/5f074244-481c-43d9-af97-3357e8b84fc0";
  #    fsType = "ext4";
  #  };

  #fileSystems."/boot" =
  #  { device = "/dev/disk/by-uuid/64B7-F7EB";
  #    fsType = "vfat";
  #    options = [ "fmask=0022" "dmask=0022" ];
  #  };

  #swapDevices = [ ];

  ## Harddrives
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
      options = [ "noatime" ];
    };
    "/boot" = {
      device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
    };
    "/backup" = {
      device = "/dev/disk/by-label/backup";
      fsType = "noatime";
    };
  };

  swapDevices = [{ device = "/dev/disk/by-label/swap"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  #networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens192.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens224.useDHCP = lib.mkDefault true;
 
  networking = {
    domain = "magic.local";
    nameservers = [ "1.1.1.1" "8.8.8.8" "10.132.2.30" "10.132.2.31" ];

    #networkmanager.enable = true;

    firewall.enable = true;

    # Network
    interfaces.ens192 = {
      useDHCP = false;
      ipv4.addresses = [{
        address = "10.132.2.151";
        prefixLength = 24;
      }];
    };
    # DATA
    interfaces.ens224 = {
      useDHCP = false;
      ipv4.addresses = [{
        address = "192.168.1.221";
        prefixLength = 24;
      }];
    };

    # Gateway
    defaultGateway = {
      address = "10.132.2.254";
      interface = "ens192";
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
